name: edge
on:
  push:
  workflow_dispatch:


jobs:
  edge:
    name: edge
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: dev-drprasad/delete-tag-and-release@v0.1.2
          with:
            delete_release: true # default: false
            tag_name: edge # tag name to delete
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create a Release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: edge
            release_name: edge
            body: edge build commit=${{ github.ref }}
            prerelease: true

